on:
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Deploy"

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'  
      - run: flutter pub get
      - run: flutter test

      # Build Android APK
      - run: flutter build apk --release

      # Upload APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4  
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-web:
    name: Build & Deploy Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'  

      - run: flutter pub get
      - run: flutter test

      # Build Web
      - run: flutter build web --release

      # Deploy Web to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
