on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'

      - run: flutter pub get
      - run: flutter test

      # Build Android APK
      - run: flutter build apk --debug --split-per-abi

      # Build iOS IPA
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      # Build Flutter Web
      - run: flutter build web

      # Push to Releases
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa,build/web/**"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}

  build-web:
    name: Build & Deploy Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'

      - run: flutter pub get
      - run: flutter test

      # Build Flutter Web
      - run: flutter build web

      # Deploy to GitHub Pages (optional)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./build/web